export const types = {
    IDENTIFICAR_USUARIO: 'IDENTIFICAR_USUARIO',
    //REFRESH_USER_DATA: 'REFRESH_USER_DATA',
    SET_TOKEN: 'SET_TOKEN',
    GET_TOKEN: 'GET_TOKEN',
    REFRESH_TOKEN: 'REFRESH_TOKEN',
    TRY_RESTART_SESSION: 'TRY_RESTART_SESSION',
    LOGOUT: 'LOGOUT',
}