export const types = {
    LISTAR_MENUS_TIENDA: 'LISTAR_MENUS_TIENDA',
    FILTRAR_MENUS_TIENDA: 'FILTRAR_MENUS_TIENDA',
    FIND_MENU_TIENDA: 'FIND_MENU_TIENDA',    
    DELETE_MENU_TIENDA: 'DELETE_MENU_TIENDA',
    INSERT_MENU_TIENDA: 'INSERT_MENU_TIENDA',
    UPDATE_MENU_TIENDA: 'UPDATE_MENU_TIENDA',
    GET_ALL_MENUS_TIENDA: 'GET_ALL_MENUS_TIENDA',
    GET_MAIN_MENU_TIENDA: 'GET_MAIN_MENU_TIENDA',
}