export const types = {
    LISTAR_MARCAS: 'LISTAR_MARCAS',
    FILTRAR_MARCAS: 'FILTRAR_MARCAS',
    BUSCAR_MARCA: 'BUSCAR_MARCA',
    INSERTAR_MARCA: 'INSERTAR_MARCA',
    ACTUALIZAR_MARCA: 'ACTUALIZAR_MARCA',
    ELIMINAR_MARCA: 'ELIMINAR_MARCA',
    GET_ALL_MARCAS: 'GET_ALL_MARCAS',
    NUEVA_MARCA: 'NUEVA_MARCA',
}