export const types = {
    LISTAR_UNIDADES: 'LISTAR_UNIDADES',
    FILTRAR_UNIDADES: 'FILTRAR_UNIDADES',
    BUSCAR_UNIDADES: 'BUSCAR_UNIDADES',
    INSERTAR_UNIDADES: 'INSERTAR_UNIDADES',
    ACTUALIZAR_UNIDADES: 'ACTUALIZAR_UNIDADES',
    ELIMINAR_UNIDADES: ' ELIMINAR_UNIDADES',
    GET_ALL_UNIDADES: 'GET_ALL_UNIDADES',
    NUEVA_UNIDAD: 'NUEVA_UNIDAD',
}