export const types = {
    LISTAR_CATEGORIAS: 'LISTAR_CATEGORIAS',
    BUSCAR_CATEGORIAS: 'BUSCAR_CATEGORIAS',
    FILTRAR_CATEGORIAS: 'FILTRAR_CATEGORIAS',
    INSERTAR_CATEGORIAS: 'INSERTAR_CATEGORIAS',
    ACTUALIZAR_CATEGORIAS: 'ACTUALIZAR_CATEGORIAS',
    ELIMINAR_CATEGORIAS: 'ELIMINAR_CATEGORIAS',
    NUEVA_CATEGORIA: 'NUEVA_CATEGORIA',
    GET_ALL_CATEGORIAS: 'GET_ALL_CATEGORIAS',
}