export const types = {
    GET_DATA: 'GET_DATA',
    GET_FILTER_DATA: 'GET_FILTER_DATA',
    GET_ALL: 'GET_ALL',
    SIGUIENTE_PAGINA: 'SIGUIENTE_PAGINA',
    PAGINA_ANTERIOR: 'PAGINA_ANTERIOR',
    PRIMERA_PAGINA: 'PRIMERA_PAGINA',
    ULTIMA_PAGINA: 'ULTIMA_PAGINA',
}