export const types = {
    LISTAR_CLIENTES: 'LISTAR_CLIENTES', 
    FILTRAR_CLIENTES: 'FILTRAR_CLIENTES',
    BUSCAR_CLIENTES: 'BUSCAR_CLIENTES',
    INSERTAR_CLIENTES: 'INSERTAR_CLIENTES',
    ACTUALIZAR_CLIENTES: 'ACTUALIZAR_CLIENTES',
    ELIMINAR_CLIENTES: 'ELIMINAR_CLIENTES',  //SOFT DELETE
    ELIMINAR_REGISTRO_CLIENTES: 'ELIMINAR_REGISTRO_CLIENTES',    //ERASE RECORD
    GET_ALL_CLIENTES: 'GET_ALL_CLIENTES',
    LOGIN_CLIENTE: 'LOGIN_CLIENTE',
}