export const types = {
    LISTAR_CIUDADES: 'LISTAR_CIUDADES',
    FILTRAR_CIUDADES: 'FILTRAR_CIUDADES',
    TRAER_TODAS_CIUDADES: 'TRAER_TODAS_CIUDADES',
    TRAER_TODAS_POR_COMUNA_CIUDADES: 'TRAER_TODAS_POR_COMUNA_CIUDADES',
    INSERTAR_CIUDADES: 'INSERTAR_CIUDADES',
    ACTUALIZAR_CIUDADES: 'ACTUALIZAR_CIUDADES',
    ELIMINAR_CIUDADES: 'ELIMINAR_CIUDADES'
}