export const types = {
    LISTAR_IMPUESTOS: 'LISTAR_IMPUESTOS',
    FILTRAR_IMPUESTOS: 'FILTRAR_IMPUESTOS',
    BUSCAR_IMPUESTOS: 'BUSCAR_IMPUESTOS',
    INSERTAR_IMPUESTOS: ' INSERTAR_IMPUESTOS',
    ACTUALIZAR_IMPUESTOS: 'ACTUALIZAR_IMPUESTOS',
    ELIMINAR_IMPUESTOS: 'ELIMINAR_IMPUESTOS',
    GET_ALL_IMPUESTOS: ' GET_ALL_IMPUESTOS',
    NUEVO_IMPUESTO: 'NUEVO_IMPUESTO',
}