export const types = {
    NUEVA_SUB_CATEGORIA: 'NUEVA_SUB_CATEGORIA',
    LISTAR_SUB_CATEGORIAS: 'LISTAR_SUB_CATEGORIAS',
    LISTAR_TODAS_LAS_SUBCATEGORIAS: 'LISTAR_TODAS_LAS_SUBCATEGORIAS',
    FILTRAR_SUB_CATEGORIAS: ' FILTRAR_SUB_CATEGORIAS',
    BUSCAR_SUB_CATEGORIAS: 'BUSCAR_SUB_CATEGORIAS',
    INSERTAR_SUB_CATEGORIAS: 'INSERTAR_SUB_CATEGORIAS',
    ACTUALIZAR_SUB_CATEGORIAS: 'ACTUALIZAR_SUB_CATEGORIAS',
    ELIMINAR_SUB_CATEGORIAS: 'ELIMINAR_SUB_CATEGORIAS',
    VACIAR_LISTADO_TODAS_LAS_SUBCATEGORIAS: 'VACIAR_LISTADO_TODAS_LAS_SUBCATEGORIAS',
}