export const types = {
    LISTAR_TALLAS: 'LISTAR_TALLAS',
    FILTRAR_TALLAS: 'FILTRAR_TALLAS',
    BUSCAR_TALLAS: 'BUSCAR_TALLAS',
    OBTENER_TODAS_TALLAS: 'OBTENER_TODAS_TALLAS',
    NUEVA_TALLA: 'NUEVA_TALLA',
    INSERTAR_TALLA: 'INSERTAR_TALLA',
    ACTUALIZAR_TALLA: 'ACTUALIZAR_TALLA',
    ELIMINAR_TALLA: 'ELIMINAR_TALLA'
}