export const types = {
    PRECIOS_GET_PAGE: 'PRECIOS_GET_PAGE',
    PRECIOS_FILTER: 'PRECIOS_FILTER',
    PRECIOS_GET_ALL: 'PRECIOS_GET_ALL',
    PRECIOS_SAVE: 'PRECIOS_SAVE',
    PRECIOS_ADD_NEW: 'PRECIOS_ADD_NEW',
}