export const types = {
    NUEVO_PRODUCTO: 'NUEVO_PRODUCTO',
    LISTAR_PRODUCTOS: 'LISTAR_PRODUCTOS',
    FILTRAR_PRODUCTOS: 'FILTRAR_PRODUCTOS',
    BUSCAR_PRODUCTO: 'BUSCAR_PRODUCTOS',
    INSERTAR_PRODUCTO: 'INSERTAR_PRODUCTOS',
    ACTUALIZAR_PRODUCTO: 'ACTUALIZAR_PRODUCTO',
    ELIMINAR_PRODUCTO: 'ELIMINAR_PRODUCTO',
    GET_ALL_PRODUCTO: 'GET_ALL_PRODUCTO',
    ESTADO_INICIAL_PRODUCTO: 'ESTADO_INICIAL_PRODUCTO',
    PRECIOS_PRODUCTOS_MIN_MAX: 'PRECIOS_PRODUCTOS_MIN_MAX',
    TEXTO_FILTRO_PRODUCTO: 'TEXTO_FILTRO_PRODUCTO',
}