export const types = {
    FIND_PANTALLA: 'FIND_PANTALLA',
    DELETE_PANTALLA: 'DELETE_PANTALLA',
    INSERT_PANTALLA: 'INSERT_PANTALLA',
    UPDATE_PANTALLA: 'UPDATE_PANTALLA',
    GET_ALL_PANTALLAS: 'GET_ALL_PANTALLAS',
}