export const types = {
    LISTAR_PANTALLAS: 'LISTAR_PANTALLAS',
    FILTRAR_PANTALLAS: 'FILTRAR_PANTALLAS',
    FIND_PANTALLA: 'FIND_PANTALLA',
    DELETE_PANTALLA: 'DELETE_PANTALLA',
    INSERT_PANTALLA: 'INSERT_PANTALLA',
    UPDATE_PANTALLA: 'UPDATE_PANTALLA',
    GET_ALL_PANTALLAS: 'GET_ALL_PANTALLAS',
}