export const types = {
    GET_PAGE_SECCIONES_HOME: 'GET_PAGE_SECCIONES_HOME',
    FILTER_SECCIONES_HOME: 'FILTER_SECCIONES_HOME',
    GET_ALL_SECCIONES_HOME: 'GET_ALL_SECCIONES_HOME',
    FIND_SECCIONES_HOME: 'FIND_SECCIONES_HOME',
    INSERT_SECCIONES_HOME: 'INSERT_SECCIONES_HOME',
    UPDATE_SECCIONES_HOME: 'UPDATE_SECCIONES_HOME',
    DELETE_SECCIONES_HOME: 'DELETE_SECCIONES_HOME',
    NEW_SECCIONES_HOME: 'NEW_SECCIONES_HOME',
}