export const types = {
    LISTAR_DESPACHOS: 'LISTAR_DESPACHOS',
    FILTRAR_DESPACHOS: 'FILTRAR_DESPACHOS',
    ACTUALIZAR_DESPACHO: 'ACTUALIZAR_DESPACHO',
    CAMBIAR_ESTADO_DESPACHO: 'CAMBIAR_ESTADO_DESPACHO',
}