export const types = {
    LISTAR_USUARIOS: 'LISTAR_USUARIOS',
    FILTRAR_USUARIOS: 'FILTRAR_USUARIOS',
    NUEVO_USUARIO: 'NUEVO_USUARIO',
    INSERTAR_USUARIO: 'INSERTAR_USUARIO',
    ACTUALIZAR_USUARIO: 'ACTUALIZAR_USUARIO',
    ELIMINAR_USUARIO: 'ELIMINAR_USUARIO',
    FILTRAR_USUARIO: 'FILTRAR_USUARIO',
    BUSCAR_USUARIO: 'BUSCAR_USUARIO',
    GET_ALL_USERS: 'GET_ALL_USERS',
}