export const types = {
    DASHBOARD_VENTAS_MENSUALES: 'DASHBOARD_VENTAS_MENSUALES',
    DASHBOARD_VENTAS_TRIMESTRALES: 'DASHBOARD_VENTAS_TRIMESTRALES',
    DASHBOARD_VENTAS_ANUALES: 'DASHBOARD_VENTAS_ANUALES',
    DASHBOARD_MAS_VENDIDOS: 'DASHBOARD_MAS_VENDIDOS',
    DASHBOARD_MENOS_VENDIDOS: 'DASHBOARD_MENOS_VENDIDOS',
    DASHBOARD_TOTALES_VENTAS_DESPACHOS: 'DASHBOARD_TOTALES_VENTAS_DESPACHOS',
    DASHBOARD_VENTAS_DESPACHOS_ULTIMO_ANIO: 'DASHBOARD_VENTAS_DESPACHOS_ULTIMO_ANIO',
}