export const types = {
    LISTAR_ROLES: 'LISTAR_ROLES',
    FILTRAR_ROLES: 'FILTRAR_ROLES',
    NUEVO_ROL: 'NUEVO_ROL',
    ELIMINAR_ROL: 'ELIMINAR_ROL',
    INSERTAR_ROL: 'INSERTAR_ROL',
    ACTUALIZAR_ROL: 'ACTUALIZAR_ROL',
    BUSCAR_ROL: 'BUSCAR_ROL',
    GET_ALL_ROLES: 'GET_ALL_ROLES',
}