export const types = {
    TIPOS_PAGO_LISTAR: 'TIPOS_PAGO_LISTAR',
    TIPOS_PAGO_FILTRAR: 'TIPOS_PAGO_FILTRAR',
    TIPOS_PAGO_BUSCAR: 'TIPOS_PAGO_BUSCAR',
    TIPOS_PAGO_INSERTAR: 'TIPOS_PAGO_INSERTAR',
    TIPOS_PAGO_ACTUALIZAR: 'TIPOS_PAGO_ACTUALIZAR',
    TIPOS_PAGO_ELIMINAR: 'TIPOS_PAGO_ELIMINAR',
    TIPOS_PAGO_GET_ALL: 'TIPOS_PAGO_GET_ALL',
    TIPOS_PAGO_NUEVO: 'TIPOS_PAGO_NUEVO',
}